#ifndef JL_ERRNO_H
#define JL_ERRNO_H

enum JudgeLightErrno {
    SUCCESS = 0,
    INIT_ERROR,

    FILE_NOT_FOUND_ERROR = 100,
    FILE_NOT_PERMISSION_ERROR,

    COMPILE_INIT_ERROR = 200,
    COMPILE_FORK_ERROR,
    COMPILE_EXEC_ERROR,
    COMPILE_EXEC_ARGS_ERROR,
    COMPILE_WAIT_ERROR,

    RUN_INIT_ERROR = 300,
    RUN_FORK_ERROR,
    RUN_EXEC_ERROR,
    RUN_EXEC_ARGS_ERROR,
    RUN_WAIT_ERROR,

    PARSER_ERROR = 400,
    PARSER_UNKNOWN_ARGS,

    SYSTEM_ERROR = 900,
};

#endif
